
default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNTNAME') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: "{{ env_var('SNOWFLAKE_ROLENAME') }}"
      database: "{{ env_var('SNOWFLAKE_DBNAME') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSENAME') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMANAME') }}"
      threads: 10
      client_session_keep_alive: False
